### ISSUE TITLE
Add timezone aliases

### ISSUE THREAD

**Issue by Phanabani** [Hawkpath/Sandpiper#113]
Examples:

```
EST -> New York
EDT -> New York
PST -> Los Angeles
Pacific -> Los Angeles
```

These make big assumptions, but they're part of common language and users have tried using them expecting them to work and they don't. After #48 is implemented, this could then display the actual timezone name to at least let people know the timezone name they're using is an assumption.

This could be implemented in the config file, like:

```yaml
bot:
  modules:
    conversion:
      timezone_aliases:
        Eastern: America/New_York
        PST: America/Los_Angeles
```
